apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chroma
spec:
  template:
    spec:
      containers:
        - name: chroma
          volumeMounts:
            - name: chroma-log-config
              mountPath: /chromadb/log_config.yml
              subPath: log_config.yml
      volumes:
        - name: chroma-log-config
          configMap:
            name: chroma-log-config

