apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chroma
spec:
  template:
    spec:
      containers:
        - name: chroma
          image: image-registry.openshift-image-registry.svc:5000/team-memory-dev/chromadb-custom:latest
          imagePullPolicy: Always
