apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chroma
spec:
  template:
    spec:
      initContainers:
        - name: init-chroma-stdout
          image: registry.access.redhat.com/ubi9/ubi-minimal:latest
          command: ["/bin/sh","-c"]
          args:
            - |
              set -e
              mkdir -p /chroma
              ln -sf /dev/stdout /chroma/chroma.log
              ls -l /chroma
          volumeMounts:
            - name: chroma-logs
              mountPath: /chroma
      containers:
        - name: chroma
          volumeMounts:
            - name: chroma-logs
              mountPath: /chroma
      volumes:
        - name: chroma-logs
          emptyDir: {}

