apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chroma
spec:
  template:
    spec:
      containers:
        - name: chroma
          command: ["python"]
          args: ["-m","chromadb.cli.cli","run","--host","0.0.0.0","--port","8000"]
