apiVersion: v1
kind: ConfigMap
metadata:
  name: chroma-log-config
data:
  log_config.yml: |
    version: 1
    formatters:
      default:
        format: "%(levelname)s: %(message)s"
    handlers:
      console:
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: default
    loggers:
      uvicorn:
        handlers: [console]
        level: INFO
        propagate: False
      uvicorn.error:
        level: INFO
      uvicorn.access:
        handlers: [console]
        level: INFO
    root:
      level: INFO
      handlers: [console]

