apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chroma
spec:
  template:
    spec:
      initContainers:
        - name: init-chroma-overlay
          image: chromadb/chroma:0.5.4
          command: ["/bin/sh","-c"]
          args:
            - |
              set -e
              PKG_DIR=$(python -c 'import chromadb, os; print(os.path.dirname(chromadb.__file__))')
              echo "Package dir: $PKG_DIR"
              mkdir -p /overlay/chromadb
              cp -r "$PKG_DIR/"* /overlay/chromadb/
              cp /config/log_config.yml /overlay/chromadb/log_config.yml
              ls -l /overlay/chromadb/log_config.yml
          volumeMounts:
            - name: chroma-pkg
              mountPath: /overlay
            - name: chroma-log-config
              mountPath: /config
      containers:
        - name: chroma
          env:
            - name: PYTHONPATH
              value: /opt/overlay
          volumeMounts:
            - name: chroma-pkg
              mountPath: /opt/overlay
      volumes:
        - name: chroma-pkg
          emptyDir: {}
        - name: chroma-log-config
          configMap:
            name: chroma-log-config
