apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chroma
spec:
  template:
    spec:
      containers:
        - name: chroma
          image: chromadb/chroma:0.5.23
          imagePullPolicy: IfNotPresent
