apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - direct-route.yaml
  - networkpolicy-allow-mcp-to-chroma.yaml
  - chroma-log-configmap.yaml
patchesStrategicMerge:
  - route-host-patch.yaml
  - pvc-size-patch.yaml
  - oauth2-proxy-scale-0.yaml
  - networkpolicy-allow-router.yaml
  - statefulset-probes-dev.yaml
  - startup-probe.yaml
  - resources-dev.yaml
  - pod-securitycontext.yaml
  - chroma-stdout-init.yaml
  - chroma-log-mount.yaml
  - chroma-log-init.yaml
  - chroma-internal-image.yaml
  # Removed chroma log patches; enforcing command via JSON6902 below
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: chroma
    path: remove-nginx-sidecar.jsonpatch.yaml
