apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chroma
spec:
  template:
    spec:
      containers:
        - name: chroma
          readinessProbe:
            $patch: replace
            httpGet:
              path: /api/v2/heartbeat
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            $patch: replace
            httpGet:
              path: /api/v2/heartbeat
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
