apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: kustomize-validate
spec:
  description: Validate kustomize overlays for dev/staging/prod
  params:
    - name: overlay
      type: string
      default: deploy/overlays/dev
  tasks:
    - name: kustomize-build
      taskSpec:
        steps:
          - name: build
            image: registry.access.redhat.com/ubi9/ubi:latest
            script: |
              #!/usr/bin/env bash
              set -euo pipefail
              dnf -y install git curl tar >/dev/null 2>&1 || true
              curl -sSL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.3/kustomize_v5.4.3_linux_amd64.tar.gz | tar -xz -C /usr/local/bin kustomize
              kustomize build $(params.overlay) >/dev/null
              echo "Validated $(params.overlay)"
