apiVersion: v1
kind: ConfigMap
metadata:
  name: chroma-nginx-proxy
data:
  chroma-proxy.conf: |
    server {
      listen 8081;
      location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Connection "";
      }
    }
