apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 50Gi
