apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chroma
  labels:
    app: chroma
spec:
  serviceName: chroma-svc
  replicas: 1
  selector:
    matchLabels:
      app: chroma
  template:
    metadata:
      labels:
        app: chroma
    spec:
      containers:
        - name: chroma
          image: chromadb/chroma:0.5.4
          imagePullPolicy: IfNotPresent
          env:
            - name: ANONYMIZED_TELEMETRY
              value: "False"
          command: ["chroma"]
          args: ["run", "--host", "0.0.0.0", "--port", "8000", "--path", "/data"]
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /api/v1/heartbeat
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/heartbeat
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: chroma-data
