apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chroma
  labels:
    app: chroma
spec:
  serviceName: chroma
  replicas: 1
  selector:
    matchLabels:
      app: chroma
  template:
    metadata:
      labels:
        app: chroma
    spec:
      containers:
        - name: chroma
          image: chromadb/chroma:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ANONYMIZED_TELEMETRY
              value: "False"
            - name: CHROMA_SERVER_HOST
              value: "0.0.0.0"
            - name: CHROMA_SERVER_HTTP_PORT
              value: "8000"
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: data
              mountPath: /chroma/chroma
          readinessProbe:
            httpGet:
              path: /api/v1/heartbeat
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/heartbeat
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: chroma-data
