apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mcp-server
  labels:
    app: mcp-server
spec:
  runPolicy: Serial
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: mcp-server:latest

