apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
spec:
  template:
    spec:
      containers:
        - name: mcp
          env:
            - name: CHROMA_URL
              value: "http://chroma-svc:8000"
