apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcp-memory
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 10Gi
